pipeline {
    agent any
    stages {



        stage('Compile') {
             steps{
                dir("demo")
                {
                   bat("mvn clean install -DskipTests")
                }



}}



stage('Running Unit Test') {
             try {steps{
                dir("demo")
                {
                   bat("mvn test -Punit")
                }




}



                                    } catch(err) {
                                        step([$class: 'JUnitResultArchiver', testResults:
                                          '**/target/surefire-reports/TEST-*UnitTest.xml'])
                                        throw err
                                    }

}

stage('Running Integration Test') {
             steps{
                dir("demo")
                {
                   bat("mvn test -Pintegration")
                }



}}

stage('Archive Build') {
             steps{
                dir("demo")
                {
                   bat("mvn package")
                }



}}

stage('Deploye TO Dev') {
             steps{
                build job:"DeployToDev"

}}

stage('Deploye TO Prod') {
             steps{
                build job:"DeployToProd"

}}




}
}


