pipeline {
    agent any
    stages {

stage('Deploye TO Dev') {
             steps{
                build job:"DeployToDev"
                 parameters: [
                        string(name: 'COMMIT_NO', value: String.valueOf(GIT_COMMIT)),
                    ]

}}

        stage('Compile') {
             steps{
                dir("demo")
                {
                   bat("mvn clean install -DskipTests")
                }



}}



stage('Running Unit Test') {
             steps{
                dir("demo")
                {
                   bat("mvn test -Punit")
                }



}}

stage('Running Integration Test') {
             steps{
                dir("demo")
                {
                   bat("mvn test -Pintegration")
                }



}}

stage('Archive Build') {
             steps{
                dir("demo")
                {
                   bat("mvn package")
                }



}}




}
}


